version: '3'

services:
  db:
    image: postgres
    container_name: real_estate_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  web:
    env_file:
      - .env
    build: ./
    container_name: real_estate_web
    restart: always
    command: bash -c "export env=${ENV} && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:5
    container_name: real_estate_redis5
    restart: always
    ports:
      - "6379:6379"