# Generated by Django 4.2.2 on 2023-08-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(max_length=1),
        ),
    ]
