# Generated by Django 4.2.2 on 2023-06-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartments.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartments.series'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.floor'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_until',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
