# Generated by Django 4.2.2 on 2023-06-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('apartments', '0004_remove_apartment_price_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='region.region'),
            preserve_default=False,
        ),
    ]
