# Generated by Django 4.2.2 on 2023-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='apartment/'),
        ),
    ]
