# Generated by Django 4.2.2 on 2023-06-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('apartments', '0006_alter_apartmentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
            preserve_default=False,
        ),
    ]
