# Generated by Django 4.2.2 on 2023-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_apartment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='plot_weaving',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='communications',
            field=models.TextField(help_text='communications', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='series',
        ),
        migrations.AddField(
            model_name='apartment',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, to='apartments.series'),
        ),
    ]
