# Generated by Django 4.2.2 on 2023-07-04 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CompanyImage',
                'verbose_name_plural': 'CompanyImages',
                'ordering': ['-created_at'],
            },
        ),
    ]
