# Generated by Django 4.2.2 on 2023-07-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
