# Generated by Django 4.2.2 on 2023-07-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('url', models.TextField(help_text='Enter a url of the social app', max_length=1000)),
                ('contacts', models.TextField(help_text='Enter a phone namber of the banner', max_length=1000)),
                ('description', models.TextField(help_text='Enter a description of the banner', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_images', to='company.company')),
            ],
            options={
                'verbose_name': 'CompanyImage',
                'verbose_name_plural': 'CompanyImages',
                'ordering': ['-created_at'],
            },
        ),
    ]
