# Generated by Django 4.2.2 on 2023-06-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ads', 'verbose_name_plural': 'Adses'},
        ),
    ]
