# Generated by Django 4.2.2 on 2023-07-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='banner.banner')),
            ],
            options={
                'verbose_name': 'ApartmentImage',
                'verbose_name_plural': 'ApartmentImages',
                'ordering': ['-created_at'],
            },
        ),
    ]
